name: CI

on:
  push:
    branches:
      - master
  # pull_request: {}

# cancel in-progress job when a new push is performed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        # version: [4.12.0, 4.14.1]
        version: [4.14.1]


    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: System dependencies (ubuntu)
      run: |
        sudo apt install build-essential gcc-aarch64-linux-gnu qemu-system-aarch64

    - name: Build harness
      timeout-minutes: 5
      run: |
        make build